"""Learning tab: leaderboard · regret curve · taste summary.

Renders against the current user's history. Uses ``storage.get_decision_history``
as the single source of truth for the regret curve and for the top-tags that
seed the taste summary. The bandit instance passed in supplies
``get_win_rates`` for the leaderboard.

Rendering is intentionally quiet — no hype, brand-coded cards and a single
Plotly chart. Taste summary is generated by an LLM call cached in
``st.session_state`` keyed on ``(user_id, feedback_count)`` so normal page
reruns don't re-spend tokens.
"""

from __future__ import annotations

import json
from typing import Any

import numpy as np
import plotly.graph_objects as go
import streamlit as st
from openai import OpenAI

from ..bandit import TasteBandit
from ..evaluators import EVALUATORS, evaluator_by_id
from ..storage import Storage

__all__ = ["render"]

_MONO = "'JetBrains Mono','SFMono-Regular',Menlo,Consolas,monospace"
_SERIF_ITALIC = "'Space Grotesk','Inter',system-ui,sans-serif"

INK_BLACK = "#0B0F1A"
PANEL_BG = "#12172A"
PANEL_BORDER = "#2A2F45"
AQUAMARINE = "#00F5D4"
ALABASTER = "#EAEAEA"
MUTED = "#9CA3AF"

_REGRET_THRESHOLD = 10
_TASTE_THRESHOLD = 5
_TREND_WINDOW = 10
_TREND_MIN_DELTA = 0.05  # 5 percentage points
_ARM_MIN_PULLS_FOR_TREND = 5
_RANDOM_BASELINE_SEED = 42


# ---------------------------------------------------------------- computations

def _compute_trend(positive_rates: list[bool]) -> str:
    """Given a chronological list of per-pull outcomes (True=positive reward),
    return "↑", "↓", or "→" based on last-10 vs prior-10 positive rate.

    <``_ARM_MIN_PULLS_FOR_TREND`` pulls → "calibrating".
    """
    n = len(positive_rates)
    if n < _ARM_MIN_PULLS_FOR_TREND:
        return "calibrating"
    last = positive_rates[-_TREND_WINDOW:]
    prior = positive_rates[-(2 * _TREND_WINDOW):-_TREND_WINDOW]
    if not prior:
        return "→"
    last_rate = sum(last) / len(last)
    prior_rate = sum(prior) / len(prior)
    delta = last_rate - prior_rate
    if delta > _TREND_MIN_DELTA:
        return "↑"
    if delta < -_TREND_MIN_DELTA:
        return "↓"
    return "→"


def _outcomes_by_arm(history: list[dict]) -> dict[str, list[bool]]:
    """Per-arm chronological list of positive-reward bools. No-feedback items
    are excluded so "positive rate" is measured over events that carried a signal."""
    out: dict[str, list[bool]] = {ev.id: [] for ev in EVALUATORS}
    for row in history:
        if row["feedback_reward"] is None:
            continue
        arm = row["winner_id"]
        if arm in out:
            out[arm].append(row["feedback_reward"] > 0)
    return out


def _feedback_count(history: list[dict]) -> int:
    return sum(1 for r in history if r["feedback_reward"] is not None)


def _cumulative_reward(history: list[dict]) -> list[float]:
    """Chronological cumulative sum of observed feedback rewards.
    Items with no feedback contribute 0 to the running total."""
    cum: list[float] = []
    running = 0.0
    for row in history:
        r = row["feedback_reward"] or 0.0
        running += float(r)
        cum.append(running)
    return cum


def _random_baseline_cumulative(history: list[dict]) -> list[float]:
    """Deterministic baseline: for each decision where feedback exists,
    if the randomly-picked arm matches the actual winner we keep the
    observed reward; otherwise we draw a random reward from the empirical
    reward distribution observed so far.

    Deterministic because we fix the seed at ``_RANDOM_BASELINE_SEED``.
    This is an honest baseline for "what if winners were picked uniformly
    at random" — it doesn't pretend the random policy would have observed
    a different reward for an item the user never rated.
    """
    rng = np.random.default_rng(_RANDOM_BASELINE_SEED)
    arm_ids = [ev.id for ev in EVALUATORS]
    cum: list[float] = []
    running = 0.0
    observed_rewards: list[float] = []
    for row in history:
        actual = row["feedback_reward"]
        if actual is None:
            cum.append(running)
            continue
        observed_rewards.append(float(actual))
        random_arm = arm_ids[int(rng.integers(0, len(arm_ids)))]
        if random_arm == row["winner_id"]:
            running += float(actual)
        elif observed_rewards:
            # Sample from the distribution of rewards we've actually seen.
            # Early events where the pool is small skew toward recent rewards;
            # that's fine — it keeps the baseline in the same numeric range
            # as the bandit line.
            running += float(rng.choice(observed_rewards))
        cum.append(running)
    return cum


def _top_tags_split(
    history: list[dict],
    storage: Storage,
) -> tuple[list[str], list[str]]:
    """Return (positive_tags, negative_tags) — each the 3 most common topic
    tags across items with positive / negative net reward.
    Verdict tags are read from arena_results via the storage DAL."""
    positive_counts: dict[str, int] = {}
    negative_counts: dict[str, int] = {}
    for row in history:
        reward = row["feedback_reward"]
        if reward is None or reward == 0:
            continue
        arena = storage.get_arena_result(row["item_id"])
        if arena is None:
            continue
        winner_verdict = next(
            (v for v in arena.verdicts if v.evaluator_id == row["winner_id"]),
            None,
        )
        if winner_verdict is None:
            continue
        target = positive_counts if reward > 0 else negative_counts
        for tag in winner_verdict.topic_tags:
            target[tag] = target.get(tag, 0) + 1
    pos = sorted(positive_counts.items(), key=lambda kv: -kv[1])[:3]
    neg = sorted(negative_counts.items(), key=lambda kv: -kv[1])[:3]
    return [t for t, _ in pos], [t for t, _ in neg]


# ---------------------------------------------------------------- sections

def _render_leaderboard(bandit: TasteBandit, history: list[dict]) -> None:
    st.subheader("Evaluator leaderboard")
    st.caption("Which evaluator you've trusted most, and how often their picks earn a 👍.")

    win_rates = bandit.get_win_rates()
    per_arm_outcomes = _outcomes_by_arm(history)

    cols = st.columns(len(EVALUATORS))
    for col, ev in zip(cols, EVALUATORS):
        stats = win_rates.get(ev.id, {"pulls": 0, "positive_rate": 0.0})
        pulls = int(stats.get("pulls", 0))
        positive_rate = float(stats.get("positive_rate", 0.0))
        trend = _compute_trend(per_arm_outcomes.get(ev.id, []))
        trend_color = {
            "↑": "#6EE7B7",
            "↓": "#FF6B6B",
            "→": MUTED,
            "calibrating": "#FFB547",
        }.get(trend, MUTED)
        pct = int(round(positive_rate * 100))
        with col:
            st.markdown(
                f'<div class="leaderboard-card" style="padding:16px;'
                f'border:1px solid rgba(234, 234, 234, 0.1);'
                f'border-radius:12px;background:{PANEL_BG};">'
                f'<div style="font-family:\'Space Grotesk\',sans-serif;font-weight:500;'
                f'font-size:16px;color:{ALABASTER};margin-bottom:10px;">'
                f'{ev.avatar} {ev.name.upper()}</div>'
                f'<div class="mono" style="color:{ev.color};font-size:32px;'
                f'font-weight:700;line-height:1.1;">{pulls}</div>'
                f'<div class="mono" style="color:{MUTED};font-size:11px;margin-bottom:10px;">pulls</div>'
                f'<div class="mono" style="color:{ALABASTER};font-size:14px;">{pct}% positive</div>'
                f'<div class="mono" style="color:{trend_color};font-size:12px;margin-top:6px;">'
                f'{trend}</div>'
                f"</div>",
                unsafe_allow_html=True,
            )


def _render_regret_curve(history: list[dict]) -> None:
    st.subheader("Learning over time")
    fb_n = _feedback_count(history)
    if fb_n < _REGRET_THRESHOLD:
        st.markdown(
            f'<div style="padding:14px;border:1px dashed {PANEL_BORDER};'
            f'border-radius:10px;background:{PANEL_BG};color:{MUTED};">'
            f"Need ~10 feedback events to plot learning. You have "
            f'<span style="color:{AQUAMARINE};font-family:{_MONO};">{fb_n}</span>. '
            f"Hit 👍/👎 on more items in the Arena."
            f"</div>",
            unsafe_allow_html=True,
        )
        return

    bandit_cum = _cumulative_reward(history)
    random_cum = _random_baseline_cumulative(history)
    x = list(range(1, len(bandit_cum) + 1))

    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=x, y=bandit_cum, mode="lines", name="Bandit",
            line=dict(color=AQUAMARINE, width=2),
            hovertemplate="decision %{x}<br>cum reward %{y:.1f}<extra>Bandit</extra>",
        )
    )
    fig.add_trace(
        go.Scatter(
            x=x, y=random_cum, mode="lines", name="Random baseline",
            line=dict(color=ALABASTER, width=1.5, dash="dash"),
            opacity=0.5,
            hovertemplate="decision %{x}<br>cum reward %{y:.1f}<extra>Random</extra>",
        )
    )
    fig.update_layout(
        height=280,
        margin=dict(l=50, r=10, t=10, b=40),
        paper_bgcolor=INK_BLACK,
        plot_bgcolor=INK_BLACK,
        font=dict(family="JetBrains Mono, monospace", color=MUTED, size=11),
        xaxis=dict(
            title=dict(
                text="Decisions",
                font=dict(family="Inter, sans-serif", color=MUTED, size=11),
            ),
            showgrid=False,
            zeroline=False,
            showline=True,
            linecolor=PANEL_BORDER,
            tickfont=dict(family="JetBrains Mono, monospace"),
            tickformat=",.0f",
        ),
        yaxis=dict(
            title=dict(
                text="Cumulative reward",
                font=dict(family="Inter, sans-serif", color=MUTED, size=11),
            ),
            showgrid=False,
            zeroline=True,
            zerolinecolor=PANEL_BORDER,
            showline=False,
            tickfont=dict(family="JetBrains Mono, monospace"),
            tickformat=",.0f",
        ),
        showlegend=True,
        legend=dict(
            bgcolor=PANEL_BG,
            bordercolor=PANEL_BORDER,
            borderwidth=1,
            font=dict(color=ALABASTER, size=11),
        ),
        hovermode="x unified",
    )
    st.plotly_chart(fig, use_container_width=True, theme=None)
    st.caption("The gap between the two lines is what the system learned.")


def _render_taste_summary(
    *,
    bandit: TasteBandit,
    history: list[dict],
    storage: Storage,
    user_id: str,
    client: OpenAI | None,
) -> None:
    st.subheader("What SignalScout learned about you")
    fb_n = _feedback_count(history)
    if fb_n < _TASTE_THRESHOLD:
        st.markdown(
            f'<div style="padding:14px;border-left:3px solid {AQUAMARINE};'
            f'background:{PANEL_BG};color:{MUTED};">'
            f"SignalScout needs more signal from you to describe your taste. "
            f"Keep giving feedback in the Arena."
            f"</div>",
            unsafe_allow_html=True,
        )
        return

    cache_key = f"taste_summary:{user_id}:{fb_n}"
    summary = st.session_state.get(cache_key)
    if summary is None:
        summary = _generate_taste_summary(
            bandit=bandit,
            history=history,
            storage=storage,
            client=client,
            feedback_count=fb_n,
        )
        st.session_state[cache_key] = summary

    st.markdown(
        f'<div style="padding:14px 18px;border-left:3px solid {AQUAMARINE};'
        f'background:{PANEL_BG};color:{ALABASTER};'
        f"font-family:{_SERIF_ITALIC};font-style:italic;font-size:15px;line-height:1.5;\">"
        f"{_escape(summary)}"
        f"</div>",
        unsafe_allow_html=True,
    )


def _generate_taste_summary(
    *,
    bandit: TasteBandit,
    history: list[dict],
    storage: Storage,
    client: OpenAI | None,
    feedback_count: int,
) -> str:
    """LLM call producing a 2-3 sentence summary. Returns a fallback string
    if the client is missing or the call fails."""
    win_rates = bandit.get_win_rates()
    pos_tags, neg_tags = _top_tags_split(history, storage)

    if client is None:
        return (
            f"Taste summary needs an OpenAI key. "
            f"You've logged {feedback_count} feedback events so far."
        )

    prompt = f"""You are writing a one-paragraph summary for a user about what their
taste-learning research tool has learned about them.

Here are the bandit's current per-evaluator statistics for this user:
{json.dumps(win_rates, indent=2)}

Here are the top 3 most-frequently-appearing topic tags from items
this user gave positive feedback on:
{pos_tags}

Here are the top 3 topic tags from items they gave negative feedback on:
{neg_tags}

Write 2-3 sentences in a confident, analytical voice. No hype. No
marketing tone. Use specific numbers from the data. Start with "You
reward..." or similar direct framing. Be honest about low-confidence
findings if the sample is small (<20 feedback events).

Example tone: "You reward Scout 2.3x more on items tagged 'agents' or
'evaluation.' Skeptic's picks on methodology-heavy papers correlate
with your 👍 at 64% — above random. Confidence: medium (27 feedback events)."
"""
    try:
        resp = client.chat.completions.create(
            model="gpt-4o-mini",
            temperature=0.3,
            max_tokens=200,
            messages=[{"role": "user", "content": prompt}],
        )
        return (resp.choices[0].message.content or "").strip()
    except Exception as exc:  # surface a readable fallback, not a stacktrace
        return f"Taste summary unavailable ({type(exc).__name__}). Based on {feedback_count} feedback events."


def _escape(s: str) -> str:
    return (
        str(s or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


# ---------------------------------------------------------------- entry point

def render(
    *,
    storage: Storage,
    bandit: TasteBandit | None,
    user_id: str,
    client: OpenAI | None,
) -> None:
    """Render the Learning tab for ``user_id``.

    If the bandit is None (anonymous user path) we surface a prompt to enter
    an email — the tab is useless without a stable user id.
    """
    if not user_id or bandit is None:
        st.info(
            "Enter your email (or toggle Demo mode) in the sidebar so SignalScout "
            "can track your preferences across runs."
        )
        return

    history = storage.get_decision_history(user_id, limit=500)
    if not history:
        st.info(
            "No decisions yet. Run a brief from the **Run** tab, then come back here "
            "to see the leaderboard and learning curve."
        )
        return

    _render_leaderboard(bandit, history)
    st.markdown(
        "<hr style='border:none;border-top:1px solid #2A2F45;margin:20px 0;'>",
        unsafe_allow_html=True,
    )
    _render_regret_curve(history)
    st.markdown(
        "<hr style='border:none;border-top:1px solid #2A2F45;margin:20px 0;'>",
        unsafe_allow_html=True,
    )
    # Taste summary is wrapped separately so a failure in the LLM path — or in
    # the tag-joining helpers that feed it — never prevents the leaderboard
    # and regret curve from completing. The LLM call itself has its own
    # try/except inside _generate_taste_summary; this outer guard covers
    # everything else that runs on the taste-summary rendering path.
    try:
        _render_taste_summary(
            bandit=bandit, history=history, storage=storage, user_id=user_id, client=client,
        )
    except Exception:
        st.subheader("What SignalScout learned about you")
        st.markdown(
            f'<div style="padding:14px 18px;border-left:3px solid {AQUAMARINE};'
            f'background:{PANEL_BG};color:{MUTED};">'
            f"Taste summary unavailable — retrying shortly."
            f"</div>",
            unsafe_allow_html=True,
        )
